version: "2"
services:
  vsftpd:
    image: fauria/vsftpd
    container_name: vsftpd
    network_mode: host
    env_file: .env
    restart: unless-stopped
    ports:
      - 20:20
      - 21:21
      - 21100-21110:21100-21110
    volumes:
      - ./home:/home/vsftpd
      - ./logs:/var/log/vsftpd
